runtime: java17
instance_class: F1
service: merkand-api
entrypoint: java -Dserver.port=$PORT -jar target/api-0.0.1-SNAPSHOT.jar

env_variables:
  # Reemplaza con tu INSTANCE_CONNECTION_NAME en formato PROJECT:REGION:INSTANCE
  INSTANCE_CONNECTION_NAME: "algebraic-argon-481008-r5:europe-west2:desarrollo-cloud-instance"
  # URL JDBC usando Cloud SQL Java connector (socket factory)
  SPRING_DATASOURCE_URL: "jdbc:postgresql:///Merkand?socketFactory=com.google.cloud.sql.postgres.SocketFactory&cloudSqlInstance=${INSTANCE_CONNECTION_NAME}"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root1234@"
  JWT_SIGNING_KEY: "413F4428472B4B6250655368566D5970337336763979244226452948404D6351"