version: '3.8'

services:
  merkand-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JWT_SECRET=your-super-secret-key-here
      - DB_URL=jdbc:postgresql://db:5432/merkand
      - DB_USERNAME=merkand_user
      - DB_PASSWORD=merkand_pass
    depends_on:
      - db

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      - POSTGRES_USER=merkand_user
      - POSTGRES_PASSWORD=merkand_pass
      - POSTGRES_DB=merkand
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: