package com.merkand.api.config;

import com.merkand.api.entity.*;
import com.merkand.api.entity.enums.MovementType;
import com.merkand.api.entity.enums.Status;
import com.merkand.api.repository.OrderItemRepo;
import com.merkand.api.repository.OrderRepo;
import com.merkand.api.repository.ProductRepo;
import com.merkand.api.repository.SupplierRepo;
import com.merkand.api.repository.UserRepo;
import com.merkand.api.repository.StockMovementRepo;
import jakarta.annotation.PostConstruct;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

/**
 * Data initializer for loading test data on application startup.
 *
 * Always runs and only inserts data into a table
 * when that table is empty, so it's safe to keep across restarts.
 *
 * All dates are computed relative to the current date/time (LocalDate.now() /
 * LocalDateTime.now()) minus a fixed number of days, so the generated data
 * always looks like it happened "in the past" within roughly the last year,
 * no matter when the application is started.
 *
 * IDs are never set explicitly - they're auto-generated by JPA/Hibernate.
 * Instead of re-fetching entities by a hardcoded id (which would break once
 * ids are generated by the database), each init method returns a Map keyed
 * by a descriptive name, and later methods receive that map directly.
 */
@Component
@RequiredArgsConstructor
public class DataInitializer {

    private static final DateTimeFormatter ORDER_NUMBER_DATE_FORMAT = DateTimeFormatter.ofPattern("yyyyMMdd");

    private final UserRepo userRepo;
    private final SupplierRepo supplierRepo;
    private final ProductRepo productRepo;
    private final OrderRepo orderRepo;
    private final OrderItemRepo orderItemRepo;
    private final StockMovementRepo stockMovementRepo;

    @PostConstruct
    public void initData() {
        // All-or-nothing: if ANY table already has data, skip entirely instead
        // of trying to mix freshly-created entities with previously persisted
        // ones. Partial seeding is what caused users/orders/movements to end
        // up with mismatched (null) relationships in earlier versions of this
        // initializer
        boolean alreadySeeded = userRepo.count() > 0
                || supplierRepo.count() > 0
                || productRepo.count() > 0
                || orderRepo.count() > 0
                || orderItemRepo.count() > 0
                || stockMovementRepo.count() > 0;

        if (alreadySeeded) {
            return;
        }

        Map<String, User> users = initUsers();
        Map<String, Supplier> suppliers = initSuppliers();
        Map<String, Product> products = initProducts(suppliers);
        Map<String, Order> orders = initOrders(suppliers, users);
        initOrderItems(products, orders);
        initStockMovements(products, users);
    }

    // ---------------------------------------------------------------------
    // Date helpers - everything is anchored to "now" and shifted into the past
    // ---------------------------------------------------------------------

    private static LocalDate daysAgo(int days) {
        return LocalDate.now().minusDays(days);
    }

    private static LocalDateTime dateTimeDaysAgo(int days) {
        return LocalDateTime.now().minusDays(days);
    }

    // ---------------------------------------------------------------------
    // Entity builder helpers - reduce boilerplate for large datasets.
    // None of them set an id: it's left to JPA's auto-generation.
    // ---------------------------------------------------------------------

    private static Product createProduct(String name, String description, String category,
                                         double price, int stock, int minimumStock,
                                         String unitMeasure, String unitSale,
                                         int createdDaysAgo, int updatedDaysAgo, Supplier supplier) {
        Product product = new Product();
        product.setName(name);
        product.setDescription(description);
        product.setCategory(category);
        product.setPrice(price);
        product.setStock(stock);
        product.setMinimumStock(minimumStock);
        product.setUnitMeasure(unitMeasure);
        product.setUnitSale(unitSale);
        product.setActive(true);
        product.setCreatedAt(daysAgo(createdDaysAgo));
        product.setUpdatedAt(daysAgo(updatedDaysAgo));
        product.setSupplier(supplier);
        return product;
    }

    // sequenceNumber is only used to build the human-readable order number
    // (e.g. "P-20250101-007"); it's unrelated to the database-generated id.
    private static Order createOrder(int sequenceNumber, int orderDaysAgo, String observations, Status status,
                                     double totalAmount, Supplier supplier, User user) {
        LocalDate orderDate = daysAgo(orderDaysAgo);
        Order order = new Order();
        order.setOrderNumber("P-" + orderDate.format(ORDER_NUMBER_DATE_FORMAT) + "-" + String.format("%03d", sequenceNumber));
        order.setOrderDate(orderDate);
        order.setObservations(observations);
        order.setStatus(status);
        order.setTotalAmount(totalAmount);
        order.setSupplier(supplier);
        order.setUser(user);
        return order;
    }

    private static OrderItem createOrderItem(int quantity, double unitPrice, Order order, Product product) {
        OrderItem item = new OrderItem();
        item.setQuantity(quantity);
        item.setUnitPrice(unitPrice);
        item.setSubTotal(Math.round(quantity * unitPrice * 100.0) / 100.0);
        item.setOrder(order);
        item.setProduct(product);
        return item;
    }

    private static StockMovement createMovementHeader(MovementType type, String reference, int dateDaysAgo, User user) {
        StockMovement movement = new StockMovement();
        movement.setMovementType(type);
        movement.setReference(reference);
        movement.setDate(dateTimeDaysAgo(dateDaysAgo));
        movement.setUser(user);
        return movement;
    }

    private static MovementItem createMovementItem(int quantity, Product product, StockMovement header) {
        MovementItem item = new MovementItem();
        item.setQuantity(quantity);
        item.setProduct(product);
        item.setHeader(header);
        return item;
    }

    // ---------------------------------------------------------------------
    // Users
    // ---------------------------------------------------------------------

    private Map<String, User> initUsers() {
        // Passwords are encoded versions of "test01" and "user01"
        User admin = new User();
        admin.setUsername("test01");
        admin.setPassword("$2a$12$NvPdzjngjN6y91tRQSyg2uPfNDxvnXf8tHypt.kSfgDgIl99QBJM6");
        admin.setActive(true);
        admin.setRole(com.merkand.api.entity.enums.Role.ADMIN);

        User operator = new User();
        operator.setUsername("user01");
        operator.setPassword("$2a$12$d6kBeP64NYfSEELmB/lNOuAe/OUhVEaetZwkcKasCC.mJdR9hCy.W");
        operator.setActive(true);
        operator.setRole(com.merkand.api.entity.enums.Role.OPERATOR);

        userRepo.saveAll(List.of(admin, operator));

        Map<String, User> users = new LinkedHashMap<>();
        users.put("admin", admin);
        users.put("operator", operator);
        return users;
    }

    // ---------------------------------------------------------------------
    // Suppliers
    // ---------------------------------------------------------------------

    private Map<String, Supplier> initSuppliers() {
        Supplier supplier1 = new Supplier();
        supplier1.setName("Distribuidora Láctea del Sur");
        supplier1.setNif("B12345678");
        supplier1.setContactName("Ana Gómez");
        supplier1.setPhone("555-1234");
        supplier1.setEmail("contacto@lacteasur.com");
        supplier1.setAddress("Calle Mayor 10, Madrid");
        supplier1.setActive(true);

        Supplier supplier2 = new Supplier();
        supplier2.setName("Carnes Premium S.A.");
        supplier2.setNif("B87654321");
        supplier2.setContactName("Roberto Funes");
        supplier2.setPhone("555-5678");
        supplier2.setEmail("ventas@carnepremium.com");
        supplier2.setAddress("Av. Central 50, Barcelona");
        supplier2.setActive(true);

        Supplier supplier3 = new Supplier();
        supplier3.setName("Alimentos Frescos Hnos.");
        supplier3.setNif("B45678901");
        supplier3.setContactName("Carlos Ruiz");
        supplier3.setPhone("555-9012");
        supplier3.setEmail("pedidos@frescoshnos.com");
        supplier3.setAddress("Polígono Industrial 3, Valencia");
        supplier3.setActive(true);

        Supplier supplier4 = new Supplier();
        supplier4.setName("Bebidas Mundiales Ltda.");
        supplier4.setNif("B23456789");
        supplier4.setContactName("Marta Vidal");
        supplier4.setPhone("555-3456");
        supplier4.setEmail("info@bebidasmundiales.com");
        supplier4.setAddress("Ronda Exterior 25, Sevilla");
        supplier4.setActive(true);

        Supplier supplier5 = new Supplier();
        supplier5.setName("Fitosanitarios y Limpieza S.L.");
        supplier5.setNif("B34567890");
        supplier5.setContactName("Elena Soto");
        supplier5.setPhone("555-7788");
        supplier5.setEmail("contacto@limpiezas.es");
        supplier5.setAddress("Polígono Calle C, Bilbao");
        supplier5.setActive(true);

        Supplier supplier6 = new Supplier();
        supplier6.setName("Productos Congelados Rápidos");
        supplier6.setNif("B56789012");
        supplier6.setContactName("Javier Cano");
        supplier6.setPhone("555-2020");
        supplier6.setEmail("ventas@congeladosrapidos.net");
        supplier6.setAddress("Av. del Puerto 15, Cádiz");
        supplier6.setActive(true);

        Supplier supplier7 = new Supplier();
        supplier7.setName("Distribuidora Galega");
        supplier7.setNif("B99887766");
        supplier7.setContactName("Lucía Méndez");
        supplier7.setPhone("555-0011");
        supplier7.setEmail("pedidos@distgalega.com");
        supplier7.setAddress("Polígono Ind. Getafe, Madrid");
        supplier7.setActive(true);

        Supplier supplier8 = new Supplier();
        supplier8.setName("Suministros del Norte");
        supplier8.setNif("B55443322");
        supplier8.setContactName("Pedro San Juan");
        supplier8.setPhone("555-0022");
        supplier8.setEmail("info@sumnorte.es");
        supplier8.setAddress("Calle Norte 45, Santander");
        supplier8.setActive(true);

        supplierRepo.saveAll(List.of(
                supplier1, supplier2, supplier3, supplier4, supplier5, supplier6, supplier7, supplier8
        ));

        Map<String, Supplier> suppliers = new LinkedHashMap<>();
        suppliers.put("supplier1", supplier1); // Distribuidora Láctea del Sur
        suppliers.put("supplier2", supplier2); // Carnes Premium S.A.
        suppliers.put("supplier3", supplier3); // Alimentos Frescos Hnos.
        suppliers.put("supplier4", supplier4); // Bebidas Mundiales Ltda.
        suppliers.put("supplier5", supplier5); // Fitosanitarios y Limpieza S.L.
        suppliers.put("supplier6", supplier6); // Productos Congelados Rápidos
        suppliers.put("supplier7", supplier7); // Distribuidora Galega
        suppliers.put("supplier8", supplier8); // Suministros del Norte
        return suppliers;
    }

    // ---------------------------------------------------------------------
    // Products (28 total, spread across all 8 suppliers)
    // ---------------------------------------------------------------------

    private Map<String, Product> initProducts(Map<String, Supplier> suppliers) {
        var supplier1 = suppliers.get("supplier1");
        var supplier2 = suppliers.get("supplier2");
        var supplier3 = suppliers.get("supplier3");
        var supplier4 = suppliers.get("supplier4");
        var supplier5 = suppliers.get("supplier5");
        var supplier6 = suppliers.get("supplier6");
        var supplier7 = suppliers.get("supplier7");
        var supplier8 = suppliers.get("supplier8");

        Map<String, Product> products = new LinkedHashMap<>();

        // --- Lácteos y panadería (supplier1) ---
        products.put("leche", createProduct("Leche Entera 1L", "Leche de vaca fresca y pasteurizada", "Lácteos",
                1.15, 80, 50, "Litros", "Unidad", 340, 6, supplier1));
        products.put("yogur", createProduct("Yogur Natural Pack x6", "Yogures sin azúcar ni aditivos", "Lácteos",
                2.5, 120, 40, "Pack", "Unidad", 340, 6, supplier1));
        products.put("panMolde", createProduct("Pan de Molde Blanco", "Rebanadas grandes, sin corteza", "Panadería",
                1.75, 90, 40, "Unidad", "Unidad", 300, 6, supplier1));
        products.put("mantequilla", createProduct("Mantequilla sin Sal 250g", "Mantequilla de alta calidad", "Lácteos",
                3.1, 75, 30, "Gramos", "Unidad", 300, 6, supplier1));
        products.put("quesoManchego", createProduct("Queso Manchego 300g", "Queso curado de leche de oveja", "Lácteos",
                5.4, 60, 25, "Gramos", "Unidad", 250, 6, supplier1));
        products.put("croissant", createProduct("Croissant x4", "Bollería de mantequilla recién horneada", "Panadería",
                2.1, 60, 25, "Pack", "Pack", 200, 6, supplier1));

        // --- Carnes (supplier2) ---
        products.put("filete", createProduct("Filete de Ternera 500g", "Corte magro y tierno, envasado al vacío", "Carnes",
                8.99, 10, 20, "Gramos", "Paquete", 330, 6, supplier2));
        products.put("pechugaPollo", createProduct("Pechuga de Pollo 1kg", "Pechuga de pollo fresca sin piel", "Carnes",
                6.2, 45, 20, "Kilogramos", "Paquete", 250, 6, supplier2));
        products.put("chorizoIberico", createProduct("Chorizo Ibérico 250g", "Chorizo curado de cerdo ibérico", "Carnes",
                4.75, 70, 25, "Gramos", "Unidad", 250, 6, supplier2));

        // --- Frutas y verduras (supplier3) ---
        products.put("tomate", createProduct("Tomate Pera 1kg", "Tomates frescos de temporada", "Frutas y Verduras",
                1.8, 150, 60, "Kilogramos", "Bolsa", 320, 6, supplier3));
        products.put("lechuga", createProduct("Lechuga Romana", "Lechuga fresca, unidad", "Frutas y Verduras",
                0.95, 200, 80, "Unidad", "Unidad", 320, 6, supplier3));
        products.put("manzana", createProduct("Manzana Golden 1kg", "Manzanas dulces de temporada", "Frutas y Verduras",
                1.6, 180, 70, "Kilogramos", "Bolsa", 230, 6, supplier3));
        products.put("zanahoria", createProduct("Zanahoria 1kg", "Zanahorias frescas de huerta", "Frutas y Verduras",
                1.1, 160, 60, "Kilogramos", "Bolsa", 230, 6, supplier3));

        // --- Bebidas (supplier4) ---
        products.put("aguaMineral", createProduct("Agua Mineral 1.5L", "Pack de 6 botellas de agua mineral natural", "Bebidas",
                3.2, 300, 100, "Pack", "Pack", 310, 6, supplier4));
        products.put("cerveza", createProduct("Cerveza Lager Pack x12", "Cerveza rubia de sabor suave", "Bebidas",
                8.5, 180, 50, "Pack", "Pack", 310, 6, supplier4));
        products.put("zumoNaranja", createProduct("Zumo de Naranja 1L", "Zumo de naranja exprimido, sin azúcares añadidos", "Bebidas",
                2.3, 140, 50, "Litros", "Botella", 220, 6, supplier4));
        products.put("vinoTinto", createProduct("Vino Tinto Reserva", "Vino tinto reserva de la Ribera del Duero", "Bebidas",
                6.9, 90, 30, "Unidad", "Botella", 220, 6, supplier4));

        // --- Limpieza (supplier5) ---
        products.put("detergente", createProduct("Detergente Ropa Color", "1.5L, fórmula concentrada", "Limpieza",
                7.45, 110, 50, "Litros", "Botella", 290, 6, supplier5));
        products.put("lejia", createProduct("Lejía 2L", "Lejía desinfectante de uso general", "Limpieza",
                2.4, 130, 50, "Litros", "Botella", 200, 6, supplier5));

        // --- Congelados (supplier6) ---
        products.put("guisantes", createProduct("Guisantes Congelados 1kg", "Guisantes ultracongelados listos para cocinar", "Congelados",
                2.0, 100, 40, "Kilogramos", "Bolsa", 150, 6, supplier6));
        products.put("pizza", createProduct("Pizza Congelada Familiar", "Pizza congelada tamaño familiar, sabor barbacoa", "Congelados",
                4.5, 80, 30, "Unidad", "Unidad", 150, 6, supplier6));
        products.put("helado", createProduct("Helado de Vainilla 1L", "Helado cremoso de vainilla natural", "Congelados",
                3.8, 95, 35, "Litros", "Tarrina", 150, 6, supplier6));

        // --- Distribuidora Galega (supplier7) ---
        products.put("quesoGallego", createProduct("Queso Gallego 400g", "Queso tierno de leche de vaca gallega", "Lácteos",
                6.1, 55, 20, "Gramos", "Unidad", 100, 6, supplier7));
        products.put("empanada", createProduct("Empanada Gallega", "Empanada de atún, tamaño familiar", "Panadería",
                5.2, 40, 15, "Unidad", "Unidad", 100, 6, supplier7));
        products.put("pulpo", createProduct("Pulpo Cocido 500g", "Pulpo gallego cocido y envasado al vacío", "Mariscos",
                9.8, 25, 10, "Gramos", "Paquete", 100, 6, supplier7));

        // --- Suministros del Norte (supplier8) ---
        products.put("jabon", createProduct("Jabón de Manos 500ml", "Jabón líquido de manos, aroma neutro", "Higiene",
                1.9, 150, 50, "Mililitros", "Botella", 60, 6, supplier8));
        products.put("papelHigienico", createProduct("Papel Higiénico Pack x12", "Papel higiénico de doble hoja", "Higiene",
                5.5, 200, 80, "Pack", "Pack", 60, 6, supplier8));
        products.put("suavizante", createProduct("Suavizante Ropa 2L", "Suavizante concentrado para ropa", "Limpieza",
                3.6, 120, 45, "Litros", "Botella", 60, 6, supplier8));

        productRepo.saveAll(new ArrayList<>(products.values()));
        return products;
    }

    // ---------------------------------------------------------------------
    // Orders (22 total, cycling through all 8 suppliers)
    // ---------------------------------------------------------------------

    private Map<String, Order> initOrders(Map<String, Supplier> suppliers, Map<String, User> users) {
        var admin = users.get("admin");
        var operator = users.get("operator");

        var supplier1 = suppliers.get("supplier1");
        var supplier2 = suppliers.get("supplier2");
        var supplier3 = suppliers.get("supplier3");
        var supplier4 = suppliers.get("supplier4");
        var supplier5 = suppliers.get("supplier5");
        var supplier6 = suppliers.get("supplier6");
        var supplier7 = suppliers.get("supplier7");
        var supplier8 = suppliers.get("supplier8");

        Map<String, Order> orders = new LinkedHashMap<>();
        orders.put("order1", createOrder(1, 360, "Pedido de lácteos recibido correctamente", Status.RECEIVED, 185.0, supplier1, operator));
        orders.put("order2", createOrder(2, 340, "Carnes de calidad premium", Status.RECEIVED, 350.5, supplier2, operator));
        orders.put("order3", createOrder(3, 320, "Frutas y verduras de temporada", Status.RECEIVED, 280.95, supplier3, operator));
        orders.put("order4", createOrder(4, 300, "Reposición bebidas", Status.RECEIVED, 490.0, supplier4, operator));
        orders.put("order5", createOrder(5, 280, "Productos de limpieza para el mes", Status.RECEIVED, 650.4, supplier5, admin));
        orders.put("order6", createOrder(6, 260, "Congelados recibidos en buen estado", Status.RECEIVED, 410.25, supplier6, operator));
        orders.put("order7", createOrder(7, 240, "Primer pedido a Distribuidora Galega", Status.RECEIVED, 320.0, supplier7, admin));
        orders.put("order8", createOrder(8, 220, "Reposición higiene y limpieza", Status.RECEIVED, 275.6, supplier8, operator));
        orders.put("order9", createOrder(9, 200, "Cancelado por falta de stock del proveedor", Status.CANCELLED, 200.0, supplier1, operator));
        orders.put("order10", createOrder(10, 180, "Pedido carnes recibido sin incidencias", Status.RECEIVED, 580.0, supplier2, admin));
        orders.put("order11", createOrder(11, 160, "Reposición fruta y verdura de temporada", Status.RECEIVED, 245.3, supplier3, operator));
        orders.put("order12", createOrder(12, 140, "Pedido bebidas para eventos", Status.RECEIVED, 512.8, supplier4, admin));
        orders.put("order13", createOrder(13, 120, "Productos de limpieza recibidos", Status.RECEIVED, 398.2, supplier5, operator));
        orders.put("order14", createOrder(14, 100, "Reposición congelados mensual", Status.RECEIVED, 455.0, supplier6, admin));
        orders.put("order15", createOrder(15, 85, "Segundo pedido a Distribuidora Galega", Status.RECEIVED, 410.7, supplier7, operator));
        orders.put("order16", createOrder(16, 70, "Suministros de higiene recibidos", Status.RECEIVED, 300.15, supplier8, admin));
        orders.put("order17", createOrder(17, 55, "Pedido lácteos de reposición", Status.RECEIVED, 220.4, supplier1, operator));
        orders.put("order18", createOrder(18, 40, "Pedido carnes para fin de mes", Status.RECEIVED, 470.9, supplier2, admin));
        orders.put("order19", createOrder(19, 25, "Pedido fruta y verdura pendiente de recepción", Status.PENDING, 260.0, supplier3, operator));
        orders.put("order20", createOrder(20, 15, "Pedido bebidas programado para esta semana", Status.PENDING, 530.0, supplier4, admin));
        orders.put("order21", createOrder(21, 8, "Pedido de limpieza pendiente de confirmación", Status.PENDING, 330.5, supplier5, operator));
        orders.put("order22", createOrder(22, 3, "Cancelado, proveedor sin stock de congelados", Status.CANCELLED, 180.0, supplier6, admin));

        orderRepo.saveAll(new ArrayList<>(orders.values()));
        return orders;
    }

    // ---------------------------------------------------------------------
    // Order items - two items per order, matched to that order's supplier
    // ---------------------------------------------------------------------

    private void initOrderItems(Map<String, Product> products, Map<String, Order> orders) {
        List<OrderItem> items = new ArrayList<>(List.of(
                // Order 1 - supplier1 (Lácteos/Panadería)
                createOrderItem(100, 1.0, orders.get("order1"), products.get("leche")),
                createOrderItem(30, 2.0, orders.get("order1"), products.get("yogur")),
                // Order 2 - supplier2 (Carnes)
                createOrderItem(30, 8.5, orders.get("order2"), products.get("filete")),
                createOrderItem(25, 5.9, orders.get("order2"), products.get("pechugaPollo")),
                // Order 3 - supplier3 (Frutas y Verduras)
                createOrderItem(80, 1.6, orders.get("order3"), products.get("tomate")),
                createOrderItem(60, 0.9, orders.get("order3"), products.get("lechuga")),
                // Order 4 - supplier4 (Bebidas)
                createOrderItem(100, 3.0, orders.get("order4"), products.get("aguaMineral")),
                createOrderItem(40, 8.2, orders.get("order4"), products.get("cerveza")),
                // Order 5 - supplier5 (Limpieza)
                createOrderItem(60, 7.2, orders.get("order5"), products.get("detergente")),
                createOrderItem(50, 2.3, orders.get("order5"), products.get("lejia")),
                // Order 6 - supplier6 (Congelados)
                createOrderItem(70, 1.9, orders.get("order6"), products.get("guisantes")),
                createOrderItem(40, 4.3, orders.get("order6"), products.get("pizza")),
                // Order 7 - supplier7 (Distribuidora Galega)
                createOrderItem(30, 5.9, orders.get("order7"), products.get("quesoGallego")),
                createOrderItem(20, 5.0, orders.get("order7"), products.get("empanada")),
                // Order 8 - supplier8 (Higiene/Limpieza)
                createOrderItem(80, 1.8, orders.get("order8"), products.get("jabon")),
                createOrderItem(50, 5.3, orders.get("order8"), products.get("papelHigienico")),
                // Order 9 - supplier1, cancelado
                createOrderItem(50, 1.1, orders.get("order9"), products.get("mantequilla")),
                // Order 10 - supplier2
                createOrderItem(40, 8.6, orders.get("order10"), products.get("filete")),
                createOrderItem(35, 4.6, orders.get("order10"), products.get("chorizoIberico")),
                // Order 11 - supplier3
                createOrderItem(90, 1.5, orders.get("order11"), products.get("manzana")),
                createOrderItem(70, 1.05, orders.get("order11"), products.get("zanahoria")),
                // Order 12 - supplier4
                createOrderItem(120, 2.2, orders.get("order12"), products.get("zumoNaranja")),
                createOrderItem(30, 6.7, orders.get("order12"), products.get("vinoTinto")),
                // Order 13 - supplier5
                createOrderItem(70, 7.3, orders.get("order13"), products.get("detergente")),
                createOrderItem(40, 2.35, orders.get("order13"), products.get("lejia")),
                // Order 14 - supplier6
                createOrderItem(60, 2.0, orders.get("order14"), products.get("guisantes")),
                createOrderItem(45, 3.7, orders.get("order14"), products.get("helado")),
                // Order 15 - supplier7
                createOrderItem(35, 6.0, orders.get("order15"), products.get("quesoGallego")),
                createOrderItem(20, 9.6, orders.get("order15"), products.get("pulpo")),
                // Order 16 - supplier8
                createOrderItem(90, 1.85, orders.get("order16"), products.get("jabon")),
                createOrderItem(40, 3.5, orders.get("order16"), products.get("suavizante")),
                // Order 17 - supplier1
                createOrderItem(60, 1.1, orders.get("order17"), products.get("leche")),
                createOrderItem(25, 5.3, orders.get("order17"), products.get("quesoManchego")),
                // Order 18 - supplier2
                createOrderItem(50, 6.1, orders.get("order18"), products.get("pechugaPollo")),
                createOrderItem(40, 4.7, orders.get("order18"), products.get("chorizoIberico")),
                // Order 19 - supplier3, pendiente
                createOrderItem(100, 1.6, orders.get("order19"), products.get("tomate")),
                createOrderItem(80, 1.5, orders.get("order19"), products.get("manzana")),
                // Order 20 - supplier4, pendiente
                createOrderItem(110, 3.1, orders.get("order20"), products.get("aguaMineral")),
                createOrderItem(45, 6.8, orders.get("order20"), products.get("vinoTinto")),
                // Order 21 - supplier5, pendiente
                createOrderItem(65, 7.4, orders.get("order21"), products.get("detergente")),
                // Order 22 - supplier6, cancelado
                createOrderItem(30, 4.4, orders.get("order22"), products.get("pizza"))
        ));

        orderItemRepo.saveAll(items);
    }

    // ---------------------------------------------------------------------
    // Stock movements - IN/OUT movements covering all suppliers/products
    // ---------------------------------------------------------------------

    private void initStockMovements(Map<String, Product> products, Map<String, User> users) {
        var admin = users.get("admin");
        var operator = users.get("operator");

        List<StockMovement> movements = new ArrayList<>();

        // Movement 1: IN - lácteos de supplier1
        StockMovement movement1 = createMovementHeader(MovementType.IN, "REC-P-001", 355, operator);
        movement1.setItems(List.of(
                createMovementItem(50, products.get("leche"), movement1),
                createMovementItem(30, products.get("yogur"), movement1)
        ));
        movements.add(movement1);

        // Movement 2: IN - limpieza de supplier5
        StockMovement movement2 = createMovementHeader(MovementType.IN, "REC-P-002", 345, operator);
        movement2.setItems(List.of(
                createMovementItem(20, products.get("detergente"), movement2)
        ));
        movements.add(movement2);

        // Movement 3: OUT - venta de carnes y verduras
        StockMovement movement3 = createMovementHeader(MovementType.OUT, "VENTA-001", 300, admin);
        movement3.setItems(List.of(
                createMovementItem(5, products.get("filete"), movement3),
                createMovementItem(10, products.get("tomate"), movement3)
        ));
        movements.add(movement3);

        // Movement 4: IN - congelados de supplier6
        StockMovement movement4 = createMovementHeader(MovementType.IN, "REC-P-003", 200, operator);
        movement4.setItems(List.of(
                createMovementItem(40, products.get("guisantes"), movement4),
                createMovementItem(20, products.get("pizza"), movement4),
                createMovementItem(15, products.get("helado"), movement4)
        ));
        movements.add(movement4);

        // Movement 5: OUT - venta de bebidas
        StockMovement movement5 = createMovementHeader(MovementType.OUT, "VENTA-002", 150, admin);
        movement5.setItems(List.of(
                createMovementItem(30, products.get("aguaMineral"), movement5),
                createMovementItem(15, products.get("cerveza"), movement5)
        ));
        movements.add(movement5);

        // Movement 6: IN - productos de Distribuidora Galega
        StockMovement movement6 = createMovementHeader(MovementType.IN, "REC-P-004", 90, operator);
        movement6.setItems(List.of(
                createMovementItem(25, products.get("quesoGallego"), movement6),
                createMovementItem(15, products.get("empanada"), movement6),
                createMovementItem(10, products.get("pulpo"), movement6)
        ));
        movements.add(movement6);

        // Movement 7: OUT - venta de lácteos y carnes
        StockMovement movement7 = createMovementHeader(MovementType.OUT, "VENTA-003", 45, admin);
        movement7.setItems(List.of(
                createMovementItem(10, products.get("quesoManchego"), movement7),
                createMovementItem(8, products.get("pechugaPollo"), movement7)
        ));
        movements.add(movement7);

        // Movement 8: IN - higiene y limpieza de supplier8
        StockMovement movement8 = createMovementHeader(MovementType.IN, "REC-P-005", 20, operator);
        movement8.setItems(List.of(
                createMovementItem(50, products.get("jabon"), movement8),
                createMovementItem(60, products.get("papelHigienico"), movement8),
                createMovementItem(40, products.get("suavizante"), movement8)
        ));
        movements.add(movement8);

        // Movement 9: OUT - ventas recientes variadas
        StockMovement movement9 = createMovementHeader(MovementType.OUT, "VENTA-004", 5, admin);
        movement9.setItems(List.of(
                createMovementItem(10, products.get("leche"), movement9),
                createMovementItem(15, products.get("aguaMineral"), movement9),
                createMovementItem(5, products.get("guisantes"), movement9)
        ));
        movements.add(movement9);

        stockMovementRepo.saveAll(movements);
    }
}